### ISSUE TITLE
装到 alfred3 不好用

### ISSUE THREAD

**Issue by fenghlkevin** [hyacz/QQ-Alfred-Workflow#1]
装到了 alfred3 ,qq版本 6.0.1 （27820）

**Comment by hyacz** [comment]
抱歉，QQ更新之后没有及时适配。这两天我会适配上的。

**Comment by fenghlkevin** [comment]
辛苦了，非常感谢

**Comment by hyacz** [comment]
已经适配上了，你可以测试一下。  
主要问题在于QQ新增了一个拖拽发送文件的窗口，导致原有的主窗口index发生变化了，workflow就挂了。  查找联系人的方式从原有的找UI元素直接设置属性的方式改为了command + F加模拟键盘输入的方式，应该会健壮一些。

**Comment by fenghlkevin** [comment]
已经测试通过了。非常感谢
