### ISSUE TITLE
Search QQ Contacts 执行时报错

### ISSUE THREAD

**Issue by kuankuanlv** [hyacz/QQ-Alfred-Workflow#3]
![image](https://user-images.githubusercontent.com/19601210/39562020-e307bc4e-4edb-11e8-90e0-5f96e81a51c6.png)

**Comment by hyacz** [comment]
似乎是由于QQ版本更新去掉了Send to的窗格导致的windows序号发生变化的问题，原来的脚本使用了比较粗暴的方式直接去获取窗口元素。周末的时候我会考虑一下是否有更好的办法彻底解决这个问题。

**Comment by hyacz** [comment]
这个问题应该在新版中得到了解决，并支持了中文的搜索。
