### ISSUE TITLE
Alfred4 用不了

### ISSUE THREAD

**Issue by hanwenbo** [hyacz/QQ-Alfred-Workflow#4]

**Comment by hanwenbo** [comment]
操作快了 弹出不了

**Comment by hyacz** [comment]
我没有升级到 Alfred4 所以没针对 Alfred 4 测试过，能否提供一些更详细的信息？另外请检查 QQ 的 command + F 快捷键能否正常工作

**Comment by XYZliang** [comment]
Alfred4正常使用

**Comment by hyacz** [comment]
昨天有用户反馈了 Alfred 4 是可以正常使用的。

> 操作快了 弹出不了
如果是这个问题的话可以考虑把这个延时的值改长一些。
![image](https://user-images.githubusercontent.com/9551197/77812242-fc855780-70da-11ea-8c1d-e45e48f5635b.png)

这个 issue 太长时间没有反馈了，所以我就关闭了哈。
